// <auto-generated />
using System;
using ConferenceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225235820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ConferenceApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ConferenceApp.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttendanceConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SessionId", "UserId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("ConferenceApp.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAttendees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerBio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9436),
                            Description = "Learn the fundamentals of .NET 8 and explore new features and improvements.",
                            DurationMinutes = 60,
                            Level = 0,
                            MaxAttendees = 100,
                            Room = "Room A",
                            SessionDate = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Senior Software Engineer at Microsoft with 8 years of experience in .NET development.",
                            SpeakerName = "Sarah Johnson",
                            Technology = ".NET",
                            Title = "Getting Started with .NET 8"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9449),
                            Description = "Dive deep into advanced React patterns, hooks, and performance optimization techniques.",
                            DurationMinutes = 90,
                            Level = 2,
                            MaxAttendees = 75,
                            Room = "Room B",
                            SessionDate = new DateTime(2026, 6, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Frontend Architect with expertise in React, performance optimization, and modern JavaScript.",
                            SpeakerName = "Mark Thompson",
                            Technology = "React",
                            Title = "Advanced React Patterns and Performance"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9452),
                            Description = "Design and implement scalable microservices using Azure Container Apps and Service Bus.",
                            DurationMinutes = 75,
                            Level = 1,
                            MaxAttendees = 60,
                            Room = "Room C",
                            SessionDate = new DateTime(2026, 6, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Cloud Solutions Architect specializing in Azure and microservices architecture.",
                            SpeakerName = "Emily Chen",
                            Technology = "Azure",
                            Title = "Microservices Architecture with Azure"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9456),
                            Description = "Introduction to machine learning concepts and hands-on implementation with Python and TensorFlow.",
                            DurationMinutes = 120,
                            Level = 1,
                            MaxAttendees = 40,
                            Room = "Room D",
                            SessionDate = new DateTime(2026, 6, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Data Scientist and ML Engineer with PhD in Computer Science, 10+ years in ML research.",
                            SpeakerName = "Dr. Robert Kim",
                            Technology = "Python",
                            Title = "Machine Learning with Python and TensorFlow"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9459),
                            Description = "Learn how to implement CI/CD pipelines, automated testing, and deployment strategies using GitHub Actions.",
                            DurationMinutes = 60,
                            Level = 1,
                            MaxAttendees = 80,
                            Room = "Room A",
                            SessionDate = new DateTime(2026, 6, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "DevOps Engineer with experience in CI/CD, infrastructure as code, and cloud platforms.",
                            SpeakerName = "Alex Rodriguez",
                            Technology = "DevOps",
                            Title = "DevOps Best Practices with GitHub Actions"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9461),
                            Description = "Understanding Kubernetes concepts, deployment strategies, and container orchestration best practices.",
                            DurationMinutes = 90,
                            Level = 2,
                            MaxAttendees = 50,
                            Room = "Room B",
                            SessionDate = new DateTime(2026, 6, 16, 13, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Platform Engineer with extensive experience in Kubernetes, Docker, and cloud-native technologies.",
                            SpeakerName = "Lisa Park",
                            Technology = "Kubernetes",
                            Title = "Kubernetes Fundamentals and Container Orchestration"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9464),
                            Description = "Explore modern JavaScript features, TypeScript benefits, and advanced development patterns.",
                            DurationMinutes = 75,
                            Level = 1,
                            MaxAttendees = 90,
                            Room = "Room C",
                            SessionDate = new DateTime(2026, 6, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Full-stack developer with expertise in TypeScript, Node.js, and modern frontend frameworks.",
                            SpeakerName = "Kevin Walsh",
                            Technology = "TypeScript",
                            Title = "Modern JavaScript and TypeScript Development"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9466),
                            Description = "Security best practices, threat modeling, and implementing security controls in cloud applications.",
                            DurationMinutes = 60,
                            Level = 2,
                            MaxAttendees = 70,
                            Room = "Room D",
                            SessionDate = new DateTime(2026, 6, 17, 11, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Cybersecurity Consultant with 12+ years experience in application security and cloud security.",
                            SpeakerName = "Jennifer Martinez",
                            Technology = "Security",
                            Title = "Cybersecurity in Cloud Applications"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9469),
                            Description = "Learn GraphQL fundamentals, schema design, and how to build efficient, scalable APIs.",
                            DurationMinutes = 90,
                            Level = 1,
                            MaxAttendees = 65,
                            Room = "Room A",
                            SessionDate = new DateTime(2026, 6, 17, 13, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Backend Developer and API architect with experience in GraphQL, REST, and distributed systems.",
                            SpeakerName = "Michael Brown",
                            Technology = "GraphQL",
                            Title = "Building Scalable APIs with GraphQL"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 2, 25, 23, 58, 17, 477, DateTimeKind.Utc).AddTicks(9471),
                            Description = "Discover how AI pair programming tools can enhance productivity and code quality in modern development workflows.",
                            DurationMinutes = 45,
                            Level = 0,
                            MaxAttendees = 120,
                            Room = "Room B",
                            SessionDate = new DateTime(2026, 6, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            SpeakerBio = "Developer Advocate focusing on AI tools, developer productivity, and modern development practices.",
                            SpeakerName = "Amanda Davis",
                            Technology = "AI",
                            Title = "AI-Powered Development with GitHub Copilot"
                        });
                });

            modelBuilder.Entity("ConferenceApp.Models.SessionSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewComments")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerBio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmitterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SubmitterId");

                    b.ToTable("SessionSubmissions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConferenceApp.Models.Registration", b =>
                {
                    b.HasOne("ConferenceApp.Models.Session", "Session")
                        .WithMany("Registrations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceApp.Models.ApplicationUser", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConferenceApp.Models.SessionSubmission", b =>
                {
                    b.HasOne("ConferenceApp.Models.ApplicationUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConferenceApp.Models.ApplicationUser", "Submitter")
                        .WithMany("SessionSubmissions")
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ConferenceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ConferenceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ConferenceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceApp.Models.ApplicationUser", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("SessionSubmissions");
                });

            modelBuilder.Entity("ConferenceApp.Models.Session", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
